name: 'Setup pgvector'
description: 'Setup pgvector extension for PostgreSQL'
inputs:
  postgres-version:
    description: 'PostgreSQL version to use'
    required: false
    default: '17'
  pgvector-version:
    description: 'pgvector version to install'
    required: false
    default: '0.8.0'
runs:
  using: "composite"
  steps:
    - name: Install and Configure PostgreSQL on Ubuntu
      if: runner.os == 'Linux'
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/install-ubuntu.sh
        ${{ github.action_path }}/scripts/install-ubuntu.sh ${{ inputs.postgres-version }} ${{ inputs.pgvector-version }}

    - name: Install and Configure PostgreSQL on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/install-macos.sh
        ${{ github.action_path }}/scripts/install-macos.sh ${{ inputs.postgres-version }}

    - name: Install and Configure PostgreSQL on Windows
      if: runner.os == 'Windows'
      shell: bash
      run: |
        SCRIPT_PATH=$(echo "${{ github.action_path }}/scripts/install-windows.sh" | sed 's/\\/\//g')
        chmod +x "$SCRIPT_PATH"
        "$SCRIPT_PATH" ${{ inputs.postgres-version }} ${{ inputs.pgvector-version }}
