name: 'Setup pgvector'
description: 'Setup pgvector in GitHub Actions'
inputs:
  postgres-version:
    description: 'PostgreSQL version to use'
    required: false
    default: '17'
  pgvector-version:
    description: 'pgvector version to install'
    required: false
    default: '0.8.0'
  postgres-user:
    description: 'PostgreSQL user to create'
    required: false
    default: 'postgres'
  postgres-password:
    description: 'PostgreSQL user password'
    required: false
    default: 'postgres'
  postgres-db:
    description: 'PostgreSQL database to create'
    required: false
    default: 'postgres'
runs:
  using: "composite"
  steps:
    - name: Install and Configure PostgreSQL on Ubuntu
      if: runner.os == 'Linux'
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/install-ubuntu.sh
        ${{ github.action_path }}/scripts/install-ubuntu.sh \
          ${{ inputs.postgres-version }} \
          ${{ inputs.pgvector-version }} \
          ${{ inputs.postgres-user }} \
          ${{ inputs.postgres-password }} \
          ${{ inputs.postgres-db }}

    - name: Install and Configure PostgreSQL on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/scripts/install-macos.sh
        ${{ github.action_path }}/scripts/install-macos.sh \
          ${{ inputs.postgres-version }} \
          ${{ inputs.pgvector-version }} \
          ${{ inputs.postgres-user }} \
          ${{ inputs.postgres-password }} \
          ${{ inputs.postgres-db }}

    - name: Setup MSYS2
      if: runner.os == 'Windows'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          mingw-w64-x86_64-postgresql
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-make
          mingw-w64-x86_64-tools-git
          make
          diffutils
          git

    - name: Add MSYS2 to PATH
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        echo "D:\a\_temp\msys64\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "D:\a\_temp\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Install and Configure PostgreSQL on Windows
      if: runner.os == 'Windows'
      shell: msys2 {0}
      env:
        MSYSTEM: MINGW64
        CHERE_INVOKING: 1
      run: |
        SCRIPT_PATH=$(echo "${{ github.action_path }}/scripts/install-windows.sh" | sed 's/\\/\//g')
        chmod +x "$SCRIPT_PATH"
        "$SCRIPT_PATH" \
          ${{ inputs.postgres-version }} \
          ${{ inputs.pgvector-version }} \
          ${{ inputs.postgres-user }} \
          ${{ inputs.postgres-password }} \
          ${{ inputs.postgres-db }}
