name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, windows-latest, windows-2019, macos-latest, macos-13]
        include:
          - os: ubuntu-latest
            postgres-version: '17'
          - os: ubuntu-24.04
            postgres-version: '17'
          - os: windows-latest
            postgres-version: '17'
          - os: windows-2019
            postgres-version: '17'
          - os: macos-latest
            postgres-version: '17'
          - os: macos-13
            postgres-version: '17'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup pgvector
      uses: ./
      with:
        postgres-version: ${{ matrix.postgres-version }}

    - name: Test Extension
      run: |
        psql -d postgres -c 'CREATE EXTENSION vector;'
        psql -d postgres -c 'CREATE TABLE items (id bigserial PRIMARY KEY, embedding vector(3));'
        psql -d postgres -c 'INSERT INTO items (embedding) VALUES ('\''[1,2,3]'\'');'
        psql -d postgres -c 'SELECT * FROM items;'
